### ISSUE TITLE
Add "Hello world" example how to deploy things will CI

### ISSUE THREAD

**Issue by Nyholm** [brefphp/examples#1]
Example Github Actions, Bitbucket Pipelines, Travis or Gitlab. 

We just need to deploy the `echo "hello world";` application. The interesting thing is the CI config.

**Comment by robersonfaria** [comment]
@Nyholm could you create a bitbucket account for bref for me to use in the CI tutorial?
I'll put prints and I think this way is better.

Please add me roberson.faria@gmail.com account

**Comment by Nyholm** [comment]
I invited you as amdin

**Comment by WyriHaximus** [comment]
Would love the see the `Github Action` to do this. Currently, it looks rather daunting to deploy Bref. So a step by step guide would be most appriciated

**Comment by mnapoli** [comment]
@WyriHaximus do you mean "automated deployments" specifically?

If you mean "deployments" in general, this page can help: https://bref.sh/docs/deploy.html If I simplify it roughly, to deploy you need to run `serverless deploy`.

**Comment by WyriHaximus** [comment]
@mnapoli ok cool because it felt like there is a lot more hidden based on looking at that page.

**Comment by mnapoli** [comment]
@WyriHaximus thank you for the feedback, maybe I should move the "How it works" section lower in the page rather than start with that.

**Comment by WyriHaximus** [comment]
@mnapoli Cheers, I'll try to convert a project tonight and provide additional feedback based on that

**Comment by mnapoli** [comment]
@WyriHaximus I have edited the "Deploy" documentation to start very simply and clearly.

PR: https://github.com/brefphp/bref/pull/551

Here is a screenshot:

![Capture d’écran 2020-02-01 à 14 50 27](https://user-images.githubusercontent.com/720328/73593251-451cfc00-4502-11ea-8b9b-15fa39e94bef.png)

Hopefully that should help the next users, thank you!

**Comment by aknosis** [comment]
I think this pr can be closed, we have GitHub Actions, GitLab, and Bitbucket examples in the CI/ directory. The travis folder is empty, but could have its own issue requesting an example.

**Comment by mnapoli** [comment]
Thanks
