### ISSUE TITLE
Use new SQS transport in Messenger

### ISSUE THREAD

**Issue by vasilvestre** [brefphp/examples#23]
In symfony/symfony#32454 SQS transport have been handled, would that remove the need of bref/symfony-messenger-sqs ?

**Comment by mnapoli** [comment]
Not really, most of the work with the adapter is on the consumer side: that part is very different on AWS Lambda.

By the way here is the new package to use: https://github.com/brefphp/symfony-messenger

**Comment by vasilvestre** [comment]
Thanks ! I wasn't sure about that.
